import Foundation
import SCMACore
import SCMAReporting

/// Filesystem/configuration/reporting composition root used by the CLI and both plugins.
public struct AnalysisService: Sendable {
    public init() {}

    public func run(_ request: AnalysisRequest) async throws -> AnalysisRunResult {
        let discovery = SourceDiscovery()
        let root = try discovery.root(for: request)
        let configurationURL =
            request.configurationPath.map { URL(fileURLWithPath: $0) }
            ?? root.appendingPathComponent(".scma.json")
        var configuration = WorkspaceConfiguration()
        let hasConfiguration = FileManager.default.fileExists(atPath: configurationURL.path)
        if request.configurationPath != nil || hasConfiguration {
            do {
                let data = try Data(contentsOf: configurationURL)
                configuration = try JSONDecoder().decode(WorkspaceConfiguration.self, from: data)
            } catch let failure as AnalysisFailure {
                throw AnalysisFailure.invalidConfiguration("\(configurationURL.path): \(failure)")
            } catch let failure as DecodingError {
                throw AnalysisFailure.invalidConfiguration("\(configurationURL.path): \(describe(failure))")
            } catch {
                throw WorkspaceError("Unable to read configuration \(configurationURL.path): \(error)")
            }
        }
        let options = try configuration.analysisOptions(overrides: request)
        let selection = try discovery.select(
            request: request, root: root, excludes: configuration.exclude + request.exclude)
        let sources = try discovery.read(selection, maximumFileBytes: configuration.maximumFileBytes)
        let report = try await Analyzer().analyze(sources, options: options, jobs: request.jobs ?? configuration.jobs)
        let debtOptions = request.debtAnalysisOptions ?? configuration.debtAnalysis
            ?? (request.enableDebtAnalysis || configuration.debtValidation != nil ? DebtAnalysisOptions() : nil)
        let rankedDebtAnalysis = makeRankedDebtAnalysis(
            report: report,
            root: root,
            options: debtOptions,
            lcovPath: request.lcovPath ?? configuration.lcovPath,
            referenceTime: request.debtReferenceTime,
            pluginEvidenceLimitations: request.pluginEvidenceLimitations
        )
        let format = request.format ?? configuration.format
        let debtValidationDiagnostics = debtValidationDiagnostics(
            configuration.debtValidation,
            analysis: rankedDebtAnalysis,
            root: root
        )
        let rendered: String
        if format.isDebtReportFormat {
            guard let rankedDebtAnalysis else {
                throw AnalysisFailure.invalidConfiguration("Debt report formats require debtAnalysis configuration")
            }
            rendered = try ReportRenderer().renderDebt(rankedDebtAnalysis, format: format, graph: report.dependencyGraph)
        } else {
            let base = try ReportRenderer().render(report, format: format, root: root.path)
            rendered = format == .diagnostics ? base + debtValidationDiagnostics : base
        }
        var protectedPaths = Set(selection.entries.map { URL(fileURLWithPath: $0.path).resolvingSymlinksInPath().path })
        protectedPaths.insert(configurationURL.resolvingSymlinksInPath().path)
        if let manifest = request.manifestPath {
            protectedPaths.insert(URL(fileURLWithPath: manifest).resolvingSymlinksInPath().path)
        }
        if let output = request.outputPath {
            let url = URL(fileURLWithPath: output).standardizedFileURL.resolvingSymlinksInPath()
            guard !protectedPaths.contains(url.path), url.pathExtension != "swift" else {
                throw WorkspaceError(
                    "Refusing to overwrite a source, configuration, manifest, or Swift file with a report")
            }
            try write(rendered, to: url)
            protectedPaths.insert(url.path)
        }
        let failOnViolation = request.failOnViolation || configuration.failOnViolation
        let debtValidationFailed = debtValidationFailed(configuration.debtValidation, analysis: rankedDebtAnalysis)
        let status: Int32 = !report.complete ? 2 : ((failOnViolation && report.hasViolations) || debtValidationFailed ? 1 : 0)
        if let stamp = request.stampPath, status == 0 {
            let url = URL(fileURLWithPath: stamp).standardizedFileURL.resolvingSymlinksInPath()
            let content = "// Generated by SwiftSCMA: analysis completed. No runtime declarations.\n"
            guard url.lastPathComponent == "SCMA.analysis.swift", !protectedPaths.contains(url.path) else {
                throw WorkspaceError("Invalid build stamp path; expected an unprotected SCMA.analysis.swift")
            }
            if FileManager.default.fileExists(atPath: url.path) {
                guard try String(contentsOf: url, encoding: .utf8) == content else {
                    throw WorkspaceError("Refusing to replace an existing non-SCMA stamp")
                }
            }
            try write(content, to: url)
        }
        return AnalysisRunResult(
            report: report,
            standardOutput: request.outputPath == nil ? rendered : "",
            exitStatus: status,
            rankedDebtAnalysis: rankedDebtAnalysis
        )
    }

    private func makeRankedDebtAnalysis(
        report: AnalysisReport,
        root: URL,
        options: DebtAnalysisOptions?,
        lcovPath: String?,
        referenceTime: Date?,
        pluginEvidenceLimitations: Bool
    ) -> RankedDebtAnalysis? {
        guard let options else { return nil }
        let entities = report.debtItems.map(\.entity)
        var evidence: [DebtEvidence] = []
        if let lcovPath {
            let url = (lcovPath as NSString).isAbsolutePath
                ? URL(fileURLWithPath: lcovPath)
                : root.appendingPathComponent(lcovPath)
            do {
                let text = try String(contentsOf: url, encoding: .utf8)
                let lcov = LcovParser().parse(text)
                evidence += CoverageMatcher().match(report: lcov, entities: entities, repositoryRoot: root.path).evidence
            } catch {
                evidence += unavailableCoverageEvidence(for: entities, reason: "LCOV unavailable: \(error)")
            }
        } else if pluginEvidenceLimitations {
            evidence += unavailableCoverageEvidence(
                for: entities,
                reason: "LCOV coverage is unavailable in SwiftPM plugin context unless an accessible coverage file is configured"
            )
        }
        let history = GitHistoryEvidenceProvider().evidence(
            for: GitHistoryEvidenceRequest(
                repositoryRoot: root.path,
                referenceTime: referenceTime ?? Date(timeIntervalSince1970: 0),
                entities: entities
            )
        )
        evidence += history.evidence
        let merged = merge(evidence: evidence, into: report.debtItems)
        return DebtAnalysisBuilder(options: options).analyze(items: merged)
    }

    private func merge(evidence: [DebtEvidence], into items: [DebtItem]) -> [DebtItem] {
        guard !evidence.isEmpty else { return items }
        let grouped = Dictionary(grouping: evidence) { evidence in
            entityID(for: evidence.id)
        }
        return items.map { item in
            let mergedEvidence = (item.evidence + grouped[item.id, default: []]).sorted { lhs, rhs in
                if lhs.id != rhs.id { return lhs.id < rhs.id }
                if lhs.kind != rhs.kind { return lhs.kind < rhs.kind }
                return lhs.rawValue < rhs.rawValue
            }
            return DebtItem(id: item.id, entity: item.entity, evidence: mergedEvidence)
        }.sorted { lhs, rhs in
            if lhs.entity.level.rawValue != rhs.entity.level.rawValue {
                return lhs.entity.level.rawValue < rhs.entity.level.rawValue
            }
            return lhs.id < rhs.id
        }
    }

    private func entityID(for evidenceID: String) -> String {
        for marker in [":coverage:", ":git-history:"] {
            if let range = evidenceID.range(of: marker) {
                return String(evidenceID[..<range.lowerBound])
            }
        }
        return evidenceID
    }

    private func unavailableCoverageEvidence(for entities: [DebtEntity], reason: String) -> [DebtEvidence] {
        entities.sorted(by: entityOrder).map { entity in
            DebtEvidence(
                id: "\(entity.id):coverage:lcov",
                kind: "coverage.lcov",
                availability: .unavailable(reason: reason),
                weight: 1,
                normalizedScore: nil,
                rawValue: "unavailable",
                location: entity.location,
                note: "Coverage provider unavailable; no zero-valued risk was fabricated."
            )
        }
    }

    private func debtValidationFailed(
        _ validation: WorkspaceDebtValidation?,
        analysis: RankedDebtAnalysis?
    ) -> Bool {
        guard let validation, let analysis else { return false }
        return analysis.items.contains { item in
            guard let value = item.score.value else { return false }
            return value > validation.maxScore
        }
    }

    private func debtValidationDiagnostics(
        _ validation: WorkspaceDebtValidation?,
        analysis: RankedDebtAnalysis?,
        root: URL
    ) -> String {
        guard let validation, let analysis else { return "" }
        let failures = analysis.items.compactMap { item -> String? in
            guard let value = item.score.value, value > validation.maxScore else { return nil }
            let location = item.item.entity.location
            let file = location.file ?? "."
            let absolute = (file as NSString).isAbsolutePath ? file : root.appendingPathComponent(file).path
            let line = location.line ?? 1
            let column = location.column ?? 1
            let score = String(format: "%.1f", locale: Locale(identifier: "en_US_POSIX"), value)
            let limit = String(format: "%.1f", locale: Locale(identifier: "en_US_POSIX"), validation.maxScore)
            return "\(absolute):\(line):\(column): warning: SCMA [DEBT] \(item.item.entity.displayName): debt score \(score) exceeds \(limit)"
        }.sorted()
        return failures.isEmpty ? "" : failures.joined(separator: "\n") + "\n"
    }

    private func describe(_ error: DecodingError) -> String {
        func path(_ context: DecodingError.Context) -> String {
            let keys = context.codingPath.map(\.stringValue).joined(separator: ".")
            return keys.isEmpty ? context.debugDescription : "\(keys): \(context.debugDescription)"
        }
        switch error {
        case .typeMismatch(_, let context), .valueNotFound(_, let context), .keyNotFound(_, let context),
            .dataCorrupted(let context):
            return path(context)
        @unknown default: return "\(error)"
        }
    }

    private func write(_ content: String, to url: URL) throws {
        try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
        try content.write(to: url, atomically: true, encoding: .utf8)
    }
}
