import Foundation
import SCMACore
import SCMAReporting

/// Filesystem/configuration/reporting composition root used by the CLI and both plugins.
public struct AnalysisService: Sendable {
    public init() {}

    public func run(_ request: AnalysisRequest) async throws -> AnalysisRunResult {
        let discovery = SourceDiscovery()
        let root = try discovery.root(for: request)
        let configurationURL =
            request.configurationPath.map { URL(fileURLWithPath: $0) }
            ?? root.appendingPathComponent(".scma.json")
        var configuration = WorkspaceConfiguration()
        let hasConfiguration = FileManager.default.fileExists(atPath: configurationURL.path)
        if request.configurationPath != nil || hasConfiguration {
            do {
                let data = try Data(contentsOf: configurationURL)
                configuration = try JSONDecoder().decode(WorkspaceConfiguration.self, from: data)
            } catch let failure as AnalysisFailure {
                throw AnalysisFailure.invalidConfiguration("\(configurationURL.path): \(failure)")
            } catch let failure as DecodingError {
                throw AnalysisFailure.invalidConfiguration("\(configurationURL.path): \(describe(failure))")
            } catch {
                throw WorkspaceError("Unable to read configuration \(configurationURL.path): \(error)")
            }
        }
        let options = try configuration.analysisOptions(overrides: request)
        let selection = try discovery.select(
            request: request, root: root, excludes: configuration.exclude + request.exclude)
        let sources = try discovery.read(selection, maximumFileBytes: configuration.maximumFileBytes)
        let report = try await Analyzer().analyze(sources, options: options, jobs: request.jobs ?? configuration.jobs)
        let format = request.format ?? configuration.format
        let rendered = try ReportRenderer().render(report, format: format, root: root.path)
        var protectedPaths = Set(selection.entries.map { URL(fileURLWithPath: $0.path).resolvingSymlinksInPath().path })
        protectedPaths.insert(configurationURL.resolvingSymlinksInPath().path)
        if let manifest = request.manifestPath {
            protectedPaths.insert(URL(fileURLWithPath: manifest).resolvingSymlinksInPath().path)
        }
        if let output = request.outputPath {
            let url = URL(fileURLWithPath: output).standardizedFileURL.resolvingSymlinksInPath()
            guard !protectedPaths.contains(url.path), url.pathExtension != "swift" else {
                throw WorkspaceError(
                    "Refusing to overwrite a source, configuration, manifest, or Swift file with a report")
            }
            try write(rendered, to: url)
            protectedPaths.insert(url.path)
        }
        let failOnViolation = request.failOnViolation || configuration.failOnViolation
        let status: Int32 = !report.complete ? 2 : (failOnViolation && report.hasViolations ? 1 : 0)
        if let stamp = request.stampPath, status == 0 {
            let url = URL(fileURLWithPath: stamp).standardizedFileURL.resolvingSymlinksInPath()
            let content = "// Generated by SwiftSCMA: analysis completed. No runtime declarations.\n"
            guard url.lastPathComponent == "SCMA.analysis.swift", !protectedPaths.contains(url.path) else {
                throw WorkspaceError("Invalid build stamp path; expected an unprotected SCMA.analysis.swift")
            }
            if FileManager.default.fileExists(atPath: url.path) {
                guard try String(contentsOf: url, encoding: .utf8) == content else {
                    throw WorkspaceError("Refusing to replace an existing non-SCMA stamp")
                }
            }
            try write(content, to: url)
        }
        return AnalysisRunResult(
            report: report, standardOutput: request.outputPath == nil ? rendered : "", exitStatus: status)
    }

    private func describe(_ error: DecodingError) -> String {
        func path(_ context: DecodingError.Context) -> String {
            let keys = context.codingPath.map(\.stringValue).joined(separator: ".")
            return keys.isEmpty ? context.debugDescription : "\(keys): \(context.debugDescription)"
        }
        switch error {
        case .typeMismatch(_, let context), .valueNotFound(_, let context), .keyNotFound(_, let context),
            .dataCorrupted(let context):
            return path(context)
        @unknown default: return "\(error)"
        }
    }

    private func write(_ content: String, to url: URL) throws {
        try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
        try content.write(to: url, atomically: true, encoding: .utf8)
    }
}
