import Foundation
import SCMACore
import Testing

@Suite("SwiftPM plugin debt workflows")
struct PluginWorkflowTests {
    private let repositoryRoot = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent()
        .deletingLastPathComponent()
        .deletingLastPathComponent()

    @Test func commandAndBuildPluginsRunDebtWorkflows() throws {
        let consumer = try makePluginConsumer()
        defer { try? FileManager.default.removeItem(at: consumer) }

        try writeConfig(
            """
            {"typeScope":"nominals","jobs":1,"debtAnalysis":{"top":1}}
            """,
            in: consumer
        )

        let command = try runSwiftPackage(
            ["package", "scma", "debt", "analyze", "--target", "Demo", "--format", "json"],
            in: consumer
        )
        let report = try JSONDecoder().decode(DebtReport.self, from: Data(command.stdout.utf8))
        #expect(report.reportKind == "swiftscma-debt-report")
        #expect(report.items.count == 1)
        #expect(report.missingEvidence.contains { evidence in
            evidence.kind == "coverage.lcov" && evidence.reason.contains("SwiftPM plugin context")
        })
        #expect(report.missingEvidence.contains { evidence in
            evidence.kind.hasPrefix("git-history.") && evidence.reason.contains("not a git repository")
        })

        let debtmap = try runSwiftPackage(
            ["package", "scma", "debt", "analyze", "--target", "Demo", "--format", "debtmap-json"],
            in: consumer
        )
        let projection = try JSONDecoder().decode(DebtmapCompatibilityProjection.self, from: Data(debtmap.stdout.utf8))
        #expect(projection.projection == "debtmap-compatibility")
        #expect(projection.missingEvidence.contains { $0.kind == "coverage.lcov" })
        #expect(projection.missingEvidence.contains { evidence in
            evidence.kind.hasPrefix("git-history.") && evidence.reason.contains("not a git repository")
        })

        let successfulBuild = try runSwiftPackage(["build", "-j", "2"], in: consumer)
        #expect(successfulBuild.status == 0)
        let stamps = try stampFiles(in: consumer)
        #expect(stamps.count == 1)
        let stamp = try #require(stamps.first)
        let stampContent = try String(contentsOf: stamp, encoding: .utf8)
        #expect(stampContent == "// Generated by SwiftSCMA: analysis completed. No runtime declarations.\n")

        try writeConfig(
            """
            {"typeScope":"nominals","jobs":1,"debtAnalysis":{"top":1},"debtValidation":{"maxScore":0}}
            """,
            in: consumer
        )
        let failedBuild = try runSwiftPackage(["build", "-j", "2"], in: consumer, expectedStatus: 1)
        #expect((failedBuild.stdout + failedBuild.stderr).contains("SCMA [DEBT]"))
    }

    private func makePluginConsumer() throws -> URL {
        let root = FileManager.default.temporaryDirectory.appendingPathComponent("scma-plugin-tests-\(UUID().uuidString)")
        let sources = root.appendingPathComponent("Sources/Demo")
        try FileManager.default.createDirectory(at: sources, withIntermediateDirectories: true)
        try """
        public struct Demo {
            public init() {}
            public func run(_ value: Int) -> Int {
                if value > 10 { return value }
                if value > 5 { return value - 1 }
                if value > 0 { return value - 2 }
                return 0
            }
        }
        """.write(to: sources.appendingPathComponent("Demo.swift"), atomically: true, encoding: .utf8)
        try """
        // swift-tools-version: 6.2
        import PackageDescription

        let package = Package(
            name: "PluginConsumer",
            platforms: [.macOS(.v13)],
            products: [.library(name: "Demo", targets: ["Demo"])],
            dependencies: [.package(name: "SwiftSCMA", path: \(String(reflecting: repositoryRoot.path)))],
            targets: [
                .target(name: "Demo", plugins: [.plugin(name: "SCMABuildPlugin", package: "SwiftSCMA")])
            ]
        )
        """.write(to: root.appendingPathComponent("Package.swift"), atomically: true, encoding: .utf8)
        return root
    }

    private func writeConfig(_ contents: String, in root: URL) throws {
        try contents.write(to: root.appendingPathComponent(".scma.json"), atomically: true, encoding: .utf8)
    }

    private func runSwiftPackage(
        _ arguments: [String],
        in directory: URL,
        expectedStatus: Int32 = 0
    ) throws -> PluginRunResult {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/env")
        process.arguments = ["swift"] + arguments
        process.currentDirectoryURL = directory
        process.environment = ProcessInfo.processInfo.environment.merging([
            "CI": "1",
            "TERM": "dumb",
        ]) { _, new in new }
        let stdout = Pipe()
        let stderr = Pipe()
        process.standardOutput = stdout
        process.standardError = stderr
        try process.run()
        process.waitUntilExit()
        let result = PluginRunResult(
            status: process.terminationStatus,
            stdout: String(decoding: stdout.fileHandleForReading.readDataToEndOfFile(), as: UTF8.self),
            stderr: String(decoding: stderr.fileHandleForReading.readDataToEndOfFile(), as: UTF8.self)
        )
        #expect(
            result.status == expectedStatus,
            "swift \(arguments.joined(separator: " ")) exited \(result.status)\nstdout:\n\(result.stdout)\nstderr:\n\(result.stderr)"
        )
        return result
    }

    private func stampFiles(in root: URL) throws -> [URL] {
        let build = root.appendingPathComponent(".build")
        let enumerator = try #require(FileManager.default.enumerator(at: build, includingPropertiesForKeys: nil))
        return enumerator.compactMap { item in
            guard let url = item as? URL, url.lastPathComponent == "SCMA.analysis.swift" else { return nil }
            return url
        }.sorted { $0.path < $1.path }
    }
}

private struct PluginRunResult {
    let status: Int32
    let stdout: String
    let stderr: String
}
