import Foundation
import PackagePlugin
#if canImport(XcodeProjectPlugin)
    import XcodeProjectPlugin
#endif

@main
struct SwiftDebtBuildPlugin: BuildToolPlugin {
    func createBuildCommands(context: PluginContext, target: Target) throws -> [Command] {
        guard let target = target as? SwiftSourceModuleTarget else { return [] }
        return try commands(
            root: context.package.directoryURL, work: context.pluginWorkDirectoryURL,
            module: target.moduleName, files: target.sourceFiles.filter { $0.url.pathExtension == "swift" }.map(\.url),
            executable: context.tool(named: "swift-debt").url
        )
    }

    fileprivate func commands(
        root: URL, work: URL, module: String, files: [URL], executable: URL,
        usesXcodeCacheDriver: Bool = false
    ) throws -> [Command] {
        let inputs = files.filter { $0.lastPathComponent != "SwiftDebt.analysis.swift" }.sorted { $0.path < $1.path }
        guard !inputs.isEmpty else { return [] }
        let configuration = root.appendingPathComponent(".swift-debt.json")
        guard FileManager.default.fileExists(atPath: configuration.path) else {
            throw PluginFailure(
                "SwiftDebtBuildPlugin requires \(configuration.path) before its first build (an empty {} is valid). "
                    + "This makes configuration changes explicit SwiftPM inputs. "
                    + "The CLI and command plugin do not require this file."
            )
        }
        try FileManager.default.createDirectory(at: work, withIntermediateDirectories: true)
        let manifestURL = work.appendingPathComponent("inputs.json")
        let entries = inputs.map { Entry(path: $0.path, module: module) }
        let manifest = Manifest(root: root.path, sources: entries)
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.sortedKeys]
        let data = try encoder.encode(manifest)
        // Keep mtime stable so a no-op build does not rerun analysis.
        if (try? Data(contentsOf: manifestURL)) != data { try data.write(to: manifestURL, options: .atomic) }
        let stamp = work.appendingPathComponent("SwiftDebt.analysis.swift")
        let dependencies = inputs + [manifestURL, configuration]
        let arguments = [
            "analyze", "--manifest", manifestURL.path, "--format", "diagnostics",
            "--plugin-evidence-limitations", "--stamp", stamp.path, "--config", configuration.path,
        ]
        if usesXcodeCacheDriver {
            let driver = work.appendingPathComponent("xcode-cache-driver.sh")
            let data = Data(Self.xcodeCacheDriver.utf8)
            if (try? Data(contentsOf: driver)) != data { try data.write(to: driver, options: .atomic) }
            let fingerprintInputs = [driver] + dependencies
            let driverArguments =
                [driver.path, stamp.path, executable.path] + fingerprintInputs.map(\.path) + ["--"] + arguments
            return [
                .buildCommand(
                    displayName: "SwiftDebt metrics: \(module)",
                    executable: URL(fileURLWithPath: "/bin/sh"),
                    arguments: driverArguments,
                    inputFiles: fingerprintInputs,
                    outputFiles: [stamp]
                )
            ]
        }
        return [
            .buildCommand(
                displayName: "SwiftDebt metrics: \(module)", executable: executable, arguments: arguments,
                inputFiles: dependencies, outputFiles: [stamp]
            )
        ]
    }

    private static let xcodeCacheDriver = """
        set -eu

        stamp=$1
        tool=$2
        shift 2

        fingerprint=$(
          {
            /usr/bin/shasum -a 256 "$tool"
            while [ "$1" != "--" ]; do
              /usr/bin/shasum -a 256 "$1"
              shift
            done
            shift
            /usr/bin/printf '%s\\n' "$@"
          } | /usr/bin/shasum -a 256 | /usr/bin/awk '{print $1}'
        )

        while [ "$1" != "--" ]; do
          shift
        done
        shift

        cache_line="// SwiftDebt Xcode input fingerprint: $fingerprint"
        if [ -f "$stamp" ] && [ "$(/usr/bin/tail -n 1 "$stamp")" = "$cache_line" ]; then
          exit 0
        fi

        backup="$stamp.swiftdebt-backup"
        restore=0
        if [ -f "$stamp" ] \
          && [ "$(/usr/bin/head -n 1 "$stamp")" = "// Generated by SwiftDebt: analysis completed. No runtime declarations." ]; then
          case "$(/usr/bin/tail -n 1 "$stamp")" in
            "// SwiftDebt Xcode input fingerprint: "*)
              /bin/cp -p "$stamp" "$backup"
              /usr/bin/head -n 1 "$backup" > "$stamp"
              restore=1
              ;;
          esac
        fi

        set +e
        "$tool" "$@"
        status=$?
        set -e
        if [ "$status" -ne 0 ]; then
          if [ "$restore" -eq 1 ]; then
            /bin/mv -f "$backup" "$stamp"
          fi
          exit "$status"
        fi

        if [ "$restore" -eq 1 ]; then
          /bin/rm -f "$backup"
        fi
        /usr/bin/printf '%s\\n' "$cache_line" >> "$stamp"
        """

    private struct PluginFailure: Error, CustomStringConvertible {
        let description: String
        init(_ description: String) { self.description = description }
    }

    private struct Entry: Encodable {
        let path: String
        let module: String
    }
    private struct Manifest: Encodable {
        let root: String
        let sources: [Entry]
    }
}

#if canImport(XcodeProjectPlugin)
    extension SwiftDebtBuildPlugin: XcodeBuildToolPlugin {
        func createBuildCommands(context: XcodePluginContext, target: XcodeTarget) throws -> [Command] {
            try commands(
                root: context.xcodeProject.directoryURL, work: context.pluginWorkDirectoryURL,
                module: target.displayName,
                files: target.inputFiles.filter { $0.url.pathExtension == "swift" }.map(\.url),
                executable: context.tool(named: "swift-debt").url, usesXcodeCacheDriver: true
            )
        }
    }
#endif
