#!/usr/bin/env python3
"""Generate the current SwiftDebt changelog entry from the release plan."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from release_version_git import prepare_plan
from release_version_model import RELEASE_COMMIT, ReleaseError, ReleasePlan


HEADER = (
    "# Changelog\n\n"
    "This file is generated by `scripts/generate_changelog.py`. Do not edit it manually.\n"
)
SECTION = re.compile(
    r"(?ms)^## \[(?P<version>(?:0|[1-9][0-9]*)\."
    r"(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*))\]\n.*?(?=^## \[|\Z)"
)


def release_entry(plan: ReleasePlan) -> str:
    subjects = [subject for subject, _ in plan.commits if RELEASE_COMMIT.fullmatch(subject) is None]
    if subjects:
        changes = "\n".join(f"- {subject}" for subject in subjects)
    elif plan.base_tag is None:
        changes = "- Initial release."
    else:
        changes = "- Maintenance release."
    return f"## [{plan.target}]\n\n{changes}\n"


def updated_changelog(existing: str, plan: ReleasePlan) -> str:
    if existing and not existing.startswith(HEADER):
        raise ReleaseError("CHANGELOG.md is not managed by scripts/generate_changelog.py")
    retained = existing[len(HEADER) :] if existing else ""
    retained_sections = [
        match.group().strip() for match in SECTION.finditer(retained) if match.group("version") != str(plan.target)
    ]
    sections = [release_entry(plan).strip(), *retained_sections]
    return HEADER + "\n" + "\n\n".join(sections) + "\n"


def generate(root: Path, plan: ReleasePlan) -> bool:
    path = root / "CHANGELOG.md"
    if not plan.requires_release:
        if not path.is_file():
            raise ReleaseError("CHANGELOG.md is missing from an already released revision")
        return False
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    updated = updated_changelog(existing, plan)
    if updated == existing:
        return False
    path.write_text(updated, encoding="utf-8")
    return True


def main(arguments: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent)
    args = parser.parse_args(arguments)
    root = args.root.resolve()
    try:
        plan = prepare_plan(root)
        changed = generate(root, plan)
        state = "updated" if changed else "unchanged"
        print(f"changelog: {state} ({plan.target})")
        return 0
    except ReleaseError as error:
        print(f"changelog: FAIL: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
