#!/usr/bin/env python3
"""Verify the build plugin through a standalone downstream Xcode project."""

from __future__ import annotations

import argparse
import json
import os
import pathlib
import platform
import shutil
import subprocess
import tempfile
import time


PACKAGE_ROOT = pathlib.Path(__file__).resolve().parents[1]
FIXTURE = PACKAGE_ROOT / "Examples" / "XcodePluginConsumer"
EXPECTED_STAMP = "// Generated by SwiftDebt: analysis completed. No runtime declarations."
FINGERPRINT_PREFIX = "// SwiftDebt Xcode input fingerprint: "


def capture(command: list[str]) -> str:
    result = subprocess.run(command, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=False)
    if result.returncode != 0:
        raise AssertionError(f"Command failed ({result.returncode}): {' '.join(command)}\n{result.stdout}")
    return result.stdout.strip()


def require_environment() -> None:
    xcode = capture(["xcodebuild", "-version"])
    swift = capture(["xcrun", "swift", "--version"])
    macos = capture(["sw_vers", "-productVersion"])
    macos_build = capture(["sw_vers", "-buildVersion"])
    if not xcode.startswith("Xcode 27.0\n"):
        raise AssertionError(f"Expected Xcode 27.0, found:\n{xcode}")
    if "Apple Swift version 6.4" not in swift:
        raise AssertionError(f"Expected Apple Swift 6.4, found:\n{swift}")
    if macos.split(".", maxsplit=1)[0] != "27":
        raise AssertionError(f"Expected macOS 27, found: {macos}")
    print(xcode)
    print(swift)
    print(f"macOS {macos} ({macos_build})")


class XcodeBuilds:
    def __init__(self, consumer: pathlib.Path) -> None:
        architecture = platform.machine()
        if architecture not in {"arm64", "x86_64"}:
            raise AssertionError(f"Unsupported macOS architecture: {architecture}")
        self.logs = consumer / "logs"
        self.logs.mkdir()
        self.command = [
            "xcodebuild",
            "-project",
            str(consumer / "SwiftDebtXcodeConsumer.xcodeproj"),
            "-scheme",
            "Consumer",
            "-configuration",
            "Debug",
            "-destination",
            f"platform=macOS,arch={architecture}",
            "-derivedDataPath",
            str(consumer / "DerivedData"),
            "CODE_SIGNING_ALLOWED=NO",
        ]
        self.environment = os.environ | {"CI": "1", "TERM": "dumb"}

    def run(self, label: str, *actions: str, succeeds: bool = True) -> str:
        result = subprocess.run(
            [*self.command, *actions],
            env=self.environment,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            check=False,
        )
        (self.logs / f"{label}.log").write_text(result.stdout, encoding="utf-8")
        if succeeds and result.returncode != 0:
            raise AssertionError(f"{label} failed ({result.returncode})\n{result.stdout}")
        if not succeeds and result.returncode != 65:
            raise AssertionError(
                f"{label} returned {result.returncode}, expected Xcode build failure 65\n{result.stdout}"
            )
        print(f"PASS: {label}")
        return result.stdout


def only_stamp(derived_data: pathlib.Path) -> pathlib.Path:
    stamps = sorted(derived_data.rglob("SwiftDebt.analysis.swift"))
    if len(stamps) != 1:
        raise AssertionError(f"Expected one SwiftDebt completion file, found: {stamps}")
    lines = stamps[0].read_text(encoding="utf-8").splitlines()
    if len(lines) != 2 or lines[0] != EXPECTED_STAMP or not lines[1].startswith(FINGERPRINT_PREFIX):
        raise AssertionError(f"Unexpected completion file contents: {stamps[0]}")
    return stamps[0]


def write_after_clock_tick(path: pathlib.Path, contents: str) -> None:
    time.sleep(1.1)
    path.write_text(contents, encoding="utf-8")


def main() -> None:
    require_environment()
    build_root = PACKAGE_ROOT / ".build"
    build_root.mkdir(exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="xcode-plugin-smoke-", dir=build_root) as temporary:
        consumer = pathlib.Path(temporary)
        shutil.copytree(FIXTURE, consumer, dirs_exist_ok=True)
        builds = XcodeBuilds(consumer)
        source = consumer / "Sources" / "Consumer.swift"
        configuration = consumer / ".swift-debt.json"
        derived_data = consumer / "DerivedData"

        builds.run("clean-build", "clean", "build")
        stamp = only_stamp(derived_data)

        builds.run("warm-up", "build")
        before_no_op = stamp.stat().st_mtime_ns
        builds.run("warmed-no-op", "build")
        if stamp.stat().st_mtime_ns != before_no_op:
            raise AssertionError("Warmed no-op build reran SwiftDebt analysis")

        write_after_clock_tick(source, source.read_text(encoding="utf-8") + "\n// Source invalidation.\n")
        builds.run("source-invalidation", "build")
        after_source = stamp.stat().st_mtime_ns
        if after_source <= before_no_op:
            raise AssertionError("Source change did not rerun SwiftDebt analysis")

        write_after_clock_tick(configuration, json.dumps({"typeScope": "classes"}) + "\n")
        builds.run("configuration-invalidation", "build")
        after_configuration = stamp.stat().st_mtime_ns
        if after_configuration <= after_source:
            raise AssertionError("Configuration change did not rerun SwiftDebt analysis")

        failing = {
            "typeScope": "classes",
            "thresholds": {"CCF": 1},
            "failOnViolation": True,
        }
        write_after_clock_tick(configuration, json.dumps(failing) + "\n")
        failure_output = builds.run("failing-gate", "build", succeeds=False)
        if "SwiftDebt [CCF]" not in failure_output:
            raise AssertionError(f"Gate failed without the expected CCF diagnostic\n{failure_output}")
        if stamp.stat().st_mtime_ns != after_configuration:
            raise AssertionError("Failed analysis rewrote the successful completion file")

        failing["failOnViolation"] = False
        write_after_clock_tick(configuration, json.dumps(failing) + "\n")
        builds.run("gate-recovery", "build")
        if stamp.stat().st_mtime_ns <= after_configuration:
            raise AssertionError("Recovered build did not complete SwiftDebt analysis")
        only_stamp(derived_data)

    print("PASS: Xcode plugin clean build, warmed no-op, invalidation, gate failure, and recovery")


if __name__ == "__main__":
    argparse.ArgumentParser(description=__doc__).parse_args()
    main()
